project_id = "geenmplkdgmlovvgwzai"

[auth]
enabled = true

[database]
enabled = true

[api]
enabled = true

[functions]
enabled = true

[functions.create-user]
verify_jwt = false

[functions.assign-user-role]
verify_jwt = false

[functions.employee-invite]
verify_jwt = true

[functions.employee-payout]
verify_jwt = true

[functions.send-lead-notification]
verify_jwt = false

[functions.confirm-user]
verify_jwt = false

[functions.update-password]
verify_jwt = false
