project_id = "geenmplkdgmlovvgwzai"

[auth]
enabled = true

[database]
enabled = true

[api]
enabled = true

[functions]
enabled = true

[functions.create-user]
verify_jwt = false

[functions.assign-user-role]
verify_jwt = false
